"""add cpu_cores and cpu_count

Revision ID: 9a2490884382
Revises: 615bcf03a452
Create Date: 2025-03-20 13:11:37.399603

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a2490884382"
down_revision: str | None = "615bcf03a452"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("computer", sa.Column("cpu_count", sa.Integer(), nullable=True))
    op.add_column("cpu", sa.Column("cores", sa.Integer(), nullable=False))
    op.add_column("operatingsystem", sa.Column("os_type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operatingsystem", "os_type")
    op.drop_column("cpu", "cores")
    op.drop_column("computer", "cpu_count")
    # ### end Alembic commands ###
